<?php
namespace wscvua\lefttime;

use yii\web\AssetBundle;

class LeftTimeAsset extends AssetBundle
{
    public $sourcePath = '@ws-cv-ua/left-time';

    public $js = [
        'js/left-time.js'
    ];

    public $depends = [
        'yii\web\JqueryAsset'
    ];

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }
}